### ISSUE TITLE
Problem in line 5

### ISSUE THREAD

**Issue by mmi755** [jawher-Mansour/GPRS-Firebase#1]
In your code, can you clarify the following term(line 5)
`device=Noun_of_the_Field_you_want_to_write_your_Data_to`
What does it actually mean?

**Comment by jawher-Mansour** [comment]
So every project can have multiple devices in it , so as you can see in this pic , i have two devices (Salanka test and logs) . 
![Capture du 2020-04-02 18-40-50](https://user-images.githubusercontent.com/55153148/78280981-debc5600-7511-11ea-8437-3fa6f75faff8.png)
![Capture du 2020-04-02 18-40-10](https://user-images.githubusercontent.com/55153148/78281012-ec71db80-7511-11ea-859b-facebaa36fbf.png)
