### ISSUE TITLE
Problem inserting a float data

### ISSUE THREAD

**Issue by luisgabrielet** [jawher-Mansour/GPRS-Firebase#2]
Hello, please help me. When inserting data, in Firebase DataBase it is inserted with double quotes, for example insert data= -0.5, with AT commands, and in firebase it gives me "-0.5" .Maybe there is a possibility that the inserted data is entered without the double quotes?

Thank you very much.

**Comment by jawher-Mansour** [comment]
can you provide me a screen shot of your firebase Database
