### ISSUE TITLE
w was not declared in this scope

### ISSUE THREAD

**Issue by rafaelpascale** [jawher-Mansour/GPRS-Firebase#3]
Hi

The "w" was not declared in this scope.

I  tried string and char, but not worked

Im using esp32 and sim 800

Thanks in advanced

**Comment by jawher-Mansour** [comment]
Thanks for ur comment , i ve double checked the code , and w is supposed to be a string , but there is a ; missing ... feel free to try again i have committed the changes .

**Comment by rafaelpascale** [comment]
thanks for your answer.

I tried and the line 98 is showing "invalid conversion from 'const char*' to 'char*' [-fpermissive]"

Im tryng to send data to firebase using sim 800 L, the data is temperature and humidity, temperature and GPS
