### ISSUE TITLE
Cloud Functions deployment requieres the pay-as-you-go

### ISSUE THREAD

**Issue by pamier** [jawher-Mansour/GPRS-Firebase#4]
Hi, sorry, can you help me, when i put: firebase deploy --only functions, its say "Cloud Functions deployment requieres the pay-as-you-go (Blaze) billing plan".

what can I do?

Can do it free???

Thanks!!!

**Comment by jawher-Mansour** [comment]
well i did it for free ... so i'm not sure why this is happend to you
