### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by P3droivo** [jawher-Mansour/GPRS-Firebase#5]
Hi!

great repository!
So, I just have one question regarding the data format to upload to firebase.
So, from the .ino code I saw how you are dealing with the cloud functions. 
The unique point I didn't get is the data format.
Could you exemplify this?

Thanks in advance,

Kind regards,

Pedro

**Comment by jawher-Mansour** [comment]
[https://cdn.reverso.net/speller/v1410/IMG/cancel.svg]
Good evening,
First of all, I want to present my sincere excuses for the late reply.
Regarding the data format, it's a string that should be sent to the cloud functions. But it should be in the same format as expected in the cloud functions (Data1&data2&data3...)
waiting for your reply please accept my most distinguished regards



MANSOUR Jawher

Space & project Manager chez MakerLab

Développeur de solution IoT (LoRa , GPRS , WiFi)

Concepteur de solutions électronique embarquées

Pilote de Drone certifiée


Web :       jawher-Mansour.github.io

LinkedIn : inkedin.com/in/jawher-mansour/

Facebook : facebook.com/Jawher.Mansour

Github : github.com/jawher-Mansour

E-mail : jawhermansour@outlook.com

Tel: (+216) 50450397


________________________________
De : P3droivo <notifications@github.com>
Envoyé : dimanche 20 septembre 2020 21:51
À : jawher-Mansour/GPRS-Firebase <GPRS-Firebase@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [jawher-Mansour/GPRS-Firebase] Data format (#5)


Hi!

great repository!
So, I just have one question regarding the data format to upload to firebase.
So, from the .ino code I saw how you are dealing with the cloud functions.
The unique point I didn't get is the data format.
Could you exemplify this?

Thanks in advance,

Kind regards,

Pedro

**Comment by C6H6-FUTURE** [comment]
Good night.

Thanks for your repostory and the steps to manage firebase by cmd, I did all firebase steps, so I'm currently in the arduino code but it reply me with "Error setting the single connection" as I can understand this is because command AT+CIPMUX=0 returns error and make the sendATcommand2 function returns answer=2. For other way I probed the SIM800L apart and the command AT+CIPMUX=0 returns to me OK.

I hope that you can understand me, my english isn't good.
Thanks for your help.

**Comment by P3droivo** [comment]
Many thanks Jawher!
It works really well!
Congrats for the repository!

Kind regards,

Pedro Ivo

**Comment by jawher-Mansour** [comment]
U r welcome 👯‍♂️

**Comment by P3droivo** [comment]
Hi Jawher!

many thanks for all the previous help!
The write functions are working really well!
I just got stuck with the read one... if its ok for you, what should be the url to acess the info?
For example:
http://xxxxxxxx.cloudfunctions.net/read?device=DEVICE_NAME
is this correct?

Kind regards

Pedro Ivo

**Comment by jawher-Mansour** [comment]
Good morning and sorry again for the late reply .
i think the URL should be like this :
http://xxxxxxxx.cloudfunctions.net/read?device=DEVICE_NAME&Data_that_you_want_to_read

kind regards
jawher

**Comment by P3droivo** [comment]
Hey Jawher!

many thanks for the reply and no worries!
I tryed this url but I always get this error from firebase.

Error: DataSnapshot.child failed: First argument was an invalid path = "". Paths must be non-empty strings and can't contain ".", "#", "$", "[", or "]"
    at validatePathString (/workspace/node_modules/@firebase/database/dist/index.node.cjs.js:1667:15)
    at DataSnapshot.child (/workspace/node_modules/@firebase/database/dist/index.node.cjs.js:4290:9)
    at admin.database.ref.once.then (/workspace/index.js:57:36)
    at process._tickCallback (internal/process/next_tick.js:68:7) 

in my case the path is "device=test@test1"

Do you have any idea what should be the cause of this error with subsequent crash of the function?

Many thanks in advance!

Kind regards,

Pedro Ivo

**Comment by P3droivo** [comment]
Sorry Jawher, not "device=test@test1" but "device=test&test1".... my bad while typing...

**Comment by jawher-Mansour** [comment]
can u share a screen shot of the database?

**Comment by P3droivo** [comment]
of course!
![image](https://user-images.githubusercontent.com/23744454/97163394-57f5f180-175f-11eb-86d7-4f4adedb18ce.png)
follow attached!

**Comment by jawher-Mansour** [comment]
have u tried "device=gprsdata-315a4&test" ??

**Comment by jawher-Mansour** [comment]
sorry for making sugggestion because currently i'm working on other projects and i don't have the materials for testing :'(

**Comment by P3droivo** [comment]
Hey Jawher! No worries and sorry about the late reply!
I have already tried but no sucess :(
I am not sure the function is getting properly the data from the db. Even if I try to get the first "test" from the db it succed in the http request although the returned data length is zero like this one below

![image](https://user-images.githubusercontent.com/23744454/97494740-7fa6ae80-1945-11eb-9713-b56685c2cdc9.png)

I am not sure what I am doing wrong actually, but we will find out soon enough.
Many thanks for all the support!

Kind regards,

Pedro Ivo
